name: hjbj
favicon: null
layout_spectrum: 0.44839178607799113
typography_spectrum: 0.32802656618878245
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.0013882135972380638
  lightness: 0.18561929580755532
  saturation: 0.6137346194591373
  rhythmicContrast: 0.6259173676371574
purpose: []
